name       : xz
version    : 5.2.3
release    : 22
source     :
    - http://tukaani.org/xz/xz-5.2.3.tar.gz : 71928b357d0a09a12a4b4c5fafca8c31c19b0e7d3b8ebb19622e96f26dbf28cb
homepage   : http://tukaani.org/xz
license    :
    - GPL-2.0
summary    : xz (Data compression software)
component  : system.base
devel      : yes
optimize   :
    - speed
    - lto
emul32     : yes
description: |
    XZ Utils is a free data compression software with high compression ratio. XZ Utils is the successor to LZMA.
setup      : |
    export CFLAGS="${CFLAGS} -D_FILE_OFFSET_BITS=64"
    %configure --docdir=/usr/share/doc/xz \
               --prefix=/usr
build      : |
    %make
install    : |
    %make_install
profile    : |
    %make check
check      : |
    %make check
