name        : xz
version     : 5.0.5
release     : 8
source      :
    - http://tukaani.org/xz/xz-5.0.5.tar.gz : 5dcffe6a3726d23d1711a65288de2e215b4960da5092248ce63c99d50093b93a
homepage    : http://tukaani.org/xz
license     :
    - GPL-2.0
summary     : xz (Data compression software)
devel       : yes
optimize    : speed
description : |
    XZ Utils is a free data compression software with high compression ratio. XZ Utils is the successor to LZMA.
setup      : |
    export CFLAGS="${CFLAGS} -D_FILE_OFFSET_BITS=64"
    %configure --disable-static --docdir=/usr/share/doc/xz
build      : |
    %make
install    : |
    %make_install
