name       : xz
version    : 5.2.4
release    : 23
source     :
    - https://tukaani.org/xz/xz-5.2.4.tar.xz : 9717ae363760dedf573dad241420c5fea86256b65bc21d2cf71b2b12f0544f4b
homepage   : http://tukaani.org/xz
license    :
    - GPL-2.0
summary    : xz (Data compression software)
component  : system.base
devel      : yes
optimize   :
    - speed
    - lto
emul32     : yes
description: |
    XZ Utils is a free data compression software with high compression ratio. XZ Utils is the successor to LZMA.
setup      : |
    export CFLAGS="${CFLAGS} -D_FILE_OFFSET_BITS=64"
    %configure --docdir=/usr/share/doc/xz \
               --prefix=/usr
build      : |
    %make
install    : |
    %make_install
profile    : |
    %make check
check      : |
    %make check
