name       : xz
version    : 5.2.5
release    : 25
source     :
    - https://sourceforge.net/projects/lzmautils/files/xz-5.2.5.tar.gz/download : f6f4910fd033078738bd82bfba4f49219d03b17eb0794eb91efbae419f4aba10
homepage   : https://tukaani.org/xz/
license    : GPL-2.0-or-later
component  : system.base
summary    : xz (Data compression software)
description: |
    XZ Utils is a free data compression software with high compression ratio. XZ Utils is the successor to LZMA.
optimize   :
    - speed
    - lto
emul32     : yes
setup      : |
    export CFLAGS="${CFLAGS} -D_FILE_OFFSET_BITS=64"
    %configure
build      : |
    %make
install    : |
    %make_install
profile    : |
    %make check
check      : |
    %make check
