name       : xz
version    : 5.2.4
release    : 24
source     :
    - https://sourceforge.net/projects/lzmautils/files/xz-5.2.4.tar.gz/download : b512f3b726d3b37b6dc4c8570e137b9311e7552e8ccbab4d39d47ce5f4177145
homepage   : http://tukaani.org/xz
license    :
    - GPL-2.0
summary    : xz (Data compression software)
component  : system.base
devel      : yes
optimize   :
    - speed
    - lto
emul32     : yes
description: |
    XZ Utils is a free data compression software with high compression ratio. XZ Utils is the successor to LZMA.
setup      : |
    export CFLAGS="${CFLAGS} -D_FILE_OFFSET_BITS=64"
    %configure --docdir=/usr/share/doc/xz \
               --prefix=/usr
build      : |
    %make
install    : |
    %make_install
profile    : |
    %make check
check      : |
    %make check
