name       : xz
version    : 5.2.7
release    : 28
source     :
    - https://sourceforge.net/projects/lzmautils/files/xz-5.2.7.tar.gz/download : 06327c2ddc81e126a6d9a78b0be5014b976a2c0832f492dcfc4755d7facf6d33
homepage   : https://tukaani.org/xz/
license    : GPL-2.0-or-later
component  : system.base
summary    : xz (Data compression software)
description: |
    XZ Utils is a free data compression software with high compression ratio. XZ Utils is the successor to LZMA.
optimize   :
    - speed
    - lto
emul32     : yes
setup      : |
    export CFLAGS="${CFLAGS} -D_FILE_OFFSET_BITS=64"
    %configure
build      : |
    %make
install    : |
    %make_install
profile    : |
    %make check
check      : |
    %make check
