name       : xz
version    : 5.2.2
release    : 17
source     :
    - http://tukaani.org/xz/xz-5.2.2.tar.gz : 73df4d5d34f0468bd57d09f2d8af363e95ed6cc3a4a86129d2f2c366259902a2
homepage   : http://tukaani.org/xz
license    :
    - GPL-2.0
summary    : xz (Data compression software)
builddeps  :
    - glibc-32bit-devel
    - libgcc-32bit
devel      : yes
optimize   : speed
emul32     : yes
description: |
    XZ Utils is a free data compression software with high compression ratio. XZ Utils is the successor to LZMA.
setup      : |
    export CFLAGS="${CFLAGS} -D_FILE_OFFSET_BITS=64"
    %configure --disable-static --docdir=/usr/share/doc/xz --prefix=/usr
build      : |
    %make
install    : |
    %make_install
profile    : |
    %make check
check      : |
    %make check
